# Generated by Django 4.2.3 on 2023-07-11 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('qlanguage', models.CharField(max_length=5)),
                ('alanguage', models.CharField(max_length=5)),
                ('correct', models.BooleanField()),
                ('difficulty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
