# Generated by Django 4.2.3 on 2023-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default='something', max_length=20),
            preserve_default=False,
        ),
    ]
