# Generated by Django 4.2.3 on 2023-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0002_word_translation_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user_guess',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
